-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.27 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2013-03-23 17:16:25
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping database structure for xindi-php
DROP DATABASE IF EXISTS `xindi-php`;
CREATE DATABASE IF NOT EXISTS `xindi-php` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `xindi-php`;


-- Dumping structure for table xindi-php.articles
DROP TABLE IF EXISTS `articles`;
CREATE TABLE IF NOT EXISTS `articles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(150) NOT NULL,
  `title` varchar(150) NOT NULL,
  `content` text NOT NULL,
  `metagenerated` tinyint(4) NOT NULL,
  `metatitle` varchar(69) NOT NULL,
  `metadescription` varchar(169) NOT NULL,
  `metakeywords` varchar(169) NOT NULL,
  `author` varchar(100) NOT NULL,
  `published` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updatedby` varchar(150) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- Dumping data for table xindi-php.articles: ~2 rows (approximately)
DELETE FROM `articles`;
/*!40000 ALTER TABLE `articles` DISABLE KEYS */;
INSERT INTO `articles` (`id`, `slug`, `title`, `content`, `metagenerated`, `metatitle`, `metadescription`, `metakeywords`, `author`, `published`, `created`, `updated`, `updatedby`) VALUES
	(1, 'sed-repellendus-mollit-saepe-aspernatur', 'Sed repellendus Mollit saepe aspernatur', '<p>Cupcake ipsum dolor. Sit amet sweet roll. Cake pastry I love tart toffee drag&eacute;e drag&eacute;e candy ice cream. Bear claw toffee I love sweet roll caramels caramels sugar plum marshmallow chocolate. Cookie cotton candy I love chocolate marshmallow sesame snaps candy canes gummies bonbon. I love carrot cake sugar plum applicake. Biscuit I love croissant sweet roll candy halvah liquorice applicake liquorice. I love pie I love jelly-o. Apple pie candy canes drag&eacute;e marshmallow. I love jujubes jujubes sesame snaps toffee topping toffee pastry. Apple pie chocolate cake cheesecake pie candy canes wypas. Macaroon tiramisu halvah gummies.</p>\r\n<p>I love sweet roll I love. Pastry halvah gummies I love tart tart chocolate bar croissant oat cake. Lemon drops I love chocolate brownie cake chocolate bar tiramisu bear claw cake. Jujubes I love topping sugar plum wafer. Croissant macaroon sweet roll. Chocolate pastry lemon drops marshmallow I love wafer cheesecake. Wypas gummies tootsie roll gingerbread fruitcake. Bonbon sweet souffl&eacute; bear claw jelly-o sesame snaps pie I love fruitcake. Icing candy canes jelly beans. Lollipop chocolate bar pie marshmallow cheesecake faworki liquorice. I love jelly beans gummi bears I love. Sweet sweet roll candy canes sweet lemon drops. Brownie donut cake candy canes cheesecake halvah fruitcake. Gummi bears marshmallow jujubes I love cotton candy tart chocolate I love I love.</p>\r\n<p>Apple pie oat cake sweet roll jujubes. Carrot cake cookie tart drag&eacute;e topping cookie. Pie wypas bonbon tootsie roll cupcake I love liquorice. Lollipop cotton candy chocolate bar gingerbread applicake tiramisu marshmallow faworki. Caramels I love lemon drops tart. Gummi bears tootsie roll jujubes. Tiramisu candy cake icing jelly-o candy. Bear claw tart I love gummies jelly-o gummi bears icing tiramisu. Chupa chups halvah lemon drops cotton candy chocolate cake cheesecake applicake oat cake. Bonbon tart I love. Chocolate bar applicake carrot cake jujubes toffee. Muffin dessert icing icing chocolate cake ice cream. Tootsie roll croissant chupa chups sugar plum lollipop candy I love. Cake marshmallow wypas sweet.</p>', 0, 'Autem irure nostrud praesentium repellendus', 'Repudiandae explicabo Voluptas est consequatur', 'Nobis sit officia tempor laudantium', 'Aute consequat Repudiandae quis doloremque', '2013-03-13 00:00:00', '2013-03-13 21:17:51', '2013-03-13 21:46:11', ''),
	(2, 'aspernatur-ipsum-est-consequatur-quidem', 'Aspernatur ipsum est consequatur quidem', '<p>Cupcake ipsum dolor. Sit amet sweet roll. Cake pastry I love tart toffee drag&eacute;e drag&eacute;e candy ice cream. Bear claw toffee I love sweet roll caramels caramels sugar plum marshmallow chocolate. Cookie cotton candy I love chocolate marshmallow sesame snaps candy canes gummies bonbon. I love carrot cake sugar plum applicake. Biscuit I love croissant sweet roll candy halvah liquorice applicake liquorice. I love pie I love jelly-o. Apple pie candy canes drag&eacute;e marshmallow. I love jujubes jujubes sesame snaps toffee topping toffee pastry. Apple pie chocolate cake cheesecake pie candy canes wypas. Macaroon tiramisu halvah gummies.</p>\r\n<p>I love sweet roll I love. Pastry halvah gummies I love tart tart chocolate bar croissant oat cake. Lemon drops I love chocolate brownie cake chocolate bar tiramisu bear claw cake. Jujubes I love topping sugar plum wafer. Croissant macaroon sweet roll. Chocolate pastry lemon drops marshmallow I love wafer cheesecake. Wypas gummies tootsie roll gingerbread fruitcake. Bonbon sweet souffl&eacute; bear claw jelly-o sesame snaps pie I love fruitcake. Icing candy canes jelly beans. Lollipop chocolate bar pie marshmallow cheesecake faworki liquorice. I love jelly beans gummi bears I love. Sweet sweet roll candy canes sweet lemon drops. Brownie donut cake candy canes cheesecake halvah fruitcake. Gummi bears marshmallow jujubes I love cotton candy tart chocolate I love I love.</p>\r\n<p>Apple pie oat cake sweet roll jujubes. Carrot cake cookie tart drag&eacute;e topping cookie. Pie wypas bonbon tootsie roll cupcake I love liquorice. Lollipop cotton candy chocolate bar gingerbread applicake tiramisu marshmallow faworki. Caramels I love lemon drops tart. Gummi bears tootsie roll jujubes. Tiramisu candy cake icing jelly-o candy. Bear claw tart I love gummies jelly-o gummi bears icing tiramisu. Chupa chups halvah lemon drops cotton candy chocolate cake cheesecake applicake oat cake. Bonbon tart I love. Chocolate bar applicake carrot cake jujubes toffee. Muffin dessert icing icing chocolate cake ice cream. Tootsie roll croissant chupa chups sugar plum lollipop candy I love. Cake marshmallow wypas sweet.</p>', 0, 'Quo aliquam culpa odio quos', 'Velit eum illo rerum inventore', 'Debitis vero nisi vel rerum', 'Tempor quis officiis ut aliquam', '2013-03-12 00:00:00', '2013-03-13 21:18:03', '2013-03-13 21:46:20', '');
/*!40000 ALTER TABLE `articles` ENABLE KEYS */;


-- Dumping structure for table xindi-php.enquiries
DROP TABLE IF EXISTS `enquiries`;
CREATE TABLE IF NOT EXISTS `enquiries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `email` varchar(150) NOT NULL,
  `message` text NOT NULL,
  `isread` tinyint(4) NOT NULL,
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `created` (`created`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- Dumping data for table xindi-php.enquiries: ~1 rows (approximately)
DELETE FROM `enquiries`;
/*!40000 ALTER TABLE `enquiries` DISABLE KEYS */;
/*!40000 ALTER TABLE `enquiries` ENABLE KEYS */;


-- Dumping structure for table xindi-php.pages
DROP TABLE IF EXISTS `pages`;
CREATE TABLE IF NOT EXISTS `pages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(150) NOT NULL,
  `leftvalue` int(11) NOT NULL,
  `rightvalue` int(11) NOT NULL,
  `ancestorid` int(11) NOT NULL,
  `depth` int(11) NOT NULL,
  `title` varchar(150) NOT NULL,
  `content` text NOT NULL,
  `metagenerated` tinyint(4) NOT NULL,
  `metatitle` varchar(69) NOT NULL,
  `metadescription` varchar(169) NOT NULL,
  `metakeywords` varchar(169) NOT NULL,
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updatedby` varchar(150) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

-- Dumping data for table xindi-php.pages: ~7 rows (approximately)
DELETE FROM `pages`;
/*!40000 ALTER TABLE `pages` DISABLE KEYS */;
INSERT INTO `pages` (`id`, `slug`, `leftvalue`, `rightvalue`, `ancestorid`, `depth`, `title`, `content`, `metagenerated`, `metatitle`, `metadescription`, `metakeywords`, `created`, `updated`, `updatedby`) VALUES
	(1, '', 1, 24, 0, 0, 'Home', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\r\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\r\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, 'Home', '', '', '2013-02-01 14:54:44', '2013-03-23 09:43:29', ''),
	(2, 'sample-page-a', 2, 9, 1, 1, 'Sample Page A', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, '', '', '', '2013-03-06 14:30:13', '2013-03-06 14:30:13', ''),
	(3, 'sample-page-b', 10, 17, 1, 1, 'Sample Page B', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, '', '', '', '2013-03-06 14:30:30', '2013-03-06 14:30:30', ''),
	(4, 'sample-page-c', 18, 19, 1, 1, 'Sample Page C', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, '', '', '', '2013-03-06 14:30:43', '2013-03-06 14:30:43', ''),
	(5, 'sample-page-a/sample-page-d', 3, 4, 2, 2, 'Sample Page D', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, '', '', '', '2013-03-06 14:31:13', '2013-03-06 14:31:16', ''),
	(6, 'sample-page-a/sample-page-e', 5, 6, 2, 2, 'Sample Page E', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, '', '', '', '2013-03-06 14:31:31', '2013-03-06 14:31:31', ''),
	(8, 'sample-page-a/sample-page-f', 7, 8, 2, 2, 'Sample Page F', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, '', '', '', '2013-03-06 14:32:05', '2013-03-06 14:32:07', ''),
	(9, 'sample-page-b/sample-page-g', 11, 12, 3, 2, 'Sample Page G', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, '', '', '', '2013-03-06 14:37:10', '2013-03-06 14:37:10', ''),
	(10, 'sample-page-b/sample-page-h', 13, 14, 3, 2, 'Sample Page H', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, '', '', '', '2013-03-06 14:37:23', '2013-03-06 14:37:23', ''),
	(11, 'sample-page-b/sample-page-i', 15, 16, 3, 2, 'Sample Page I', '<p>Cupcake ipsum dolor sit amet toffee sesame snaps oat cake. Halvah tart tootsie roll croissant sesame snaps. Chocolate ice cream candy pudding I love faworki oat cake I love candy canes. I love ice cream liquorice halvah toffee liquorice. Marzipan drag&eacute;e macaroon applicake caramels carrot cake gummi bears bear claw cake. Powder sugar plum pudding icing. Muffin macaroon gingerbread apple pie carrot cake jelly beans. Apple pie cheesecake applicake apple pie I love cheesecake drag&eacute;e cupcake I love. Jelly sesame snaps jujubes tart toffee marzipan apple pie I love. Icing chocolate cake gummies sweet roll faworki applicake jelly pastry fruitcake. Croissant marzipan I love applicake. Danish faworki donut croissant faworki tiramisu brownie oat cake.</p>\n<p>Ice cream carrot cake dessert. Macaroon chocolate bar jelly faworki jelly beans sweet. Bonbon jelly powder pie jelly faworki lollipop biscuit. Cookie marshmallow souffl&eacute; carrot cake. I love biscuit applicake wafer macaroon caramels macaroon gummi bears. Chupa chups chocolate I love tootsie roll liquorice jelly. I love gummies cookie toffee dessert. Croissant toffee caramels candy powder drag&eacute;e. Carrot cake chocolate cake tart cheesecake pastry apple pie candy canes. Jelly beans brownie souffl&eacute; I love muffin chocolate bar. Donut cheesecake liquorice tart bonbon sesame snaps topping cotton candy caramels. Gummies gingerbread wypas wafer oat cake I love. Bear claw topping candy gummi bears lemon drops tart tiramisu toffee.</p>\n<p>Cookie pudding pudding ice cream. Sugar plum bear claw biscuit faworki sugar plum marzipan. Caramels cake jujubes drag&eacute;e. Candy jelly-o lollipop pie lollipop wypas. Marzipan powder chocolate. Croissant powder liquorice cookie. Wypas lollipop sesame snaps candy bear claw. Biscuit tiramisu tiramisu sweet liquorice chocolate bar sugar plum I love donut. Candy canes lemon drops apple pie I love bear claw gingerbread jelly-o. Tart jelly tootsie roll. Sesame snaps powder I love pie. Faworki cupcake cupcake muffin oat cake.</p>', 0, '', '', '', '2013-03-06 14:37:36', '2013-03-06 14:37:36', ''),
	(12, 'news', 20, 21, 1, 1, 'News', '<p>This page redirects to the news controller.</p>', 0, '', '', '', '2013-03-13 21:46:49', '2013-03-23 09:06:55', ''),
	(13, 'contact', 22, 23, 1, 1, 'Contact', '<p>This page redirects to the enquiries controller.</p>', 0, '', '', '', '2013-03-23 09:06:48', '2013-03-23 09:07:04', '');
/*!40000 ALTER TABLE `pages` ENABLE KEYS */;


-- Dumping structure for table xindi-php.users
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '',
  `email` varchar(100) NOT NULL DEFAULT '',
  `username` varchar(50) NOT NULL DEFAULT '',
  `password` varchar(100) NOT NULL DEFAULT '',
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;

-- Dumping data for table xindi-php.users: ~3 rows (approximately)
DELETE FROM `users`;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `name`, `email`, `username`, `password`, `created`, `updated`) VALUES
	(30, 'September Zimmerman', 'cytise@gmail.com', 'nikew', '4a4d993ed7bd7d467b27af52d2aaa800', '2012-12-13 13:43:35', '2012-12-13 13:44:05'),
	(31, 'Rhona Carrillo', 'xezaj@live.com', 'xorog', '5324e078ff39acf1bfb709a1675c1a86', '2012-12-13 13:48:56', '2012-12-13 13:48:56'),
	(32, 'Kylan Lloyd', 'birarisire@live.com', 'kyjuf', '5324e078ff39acf1bfb709a1675c1a86', '2012-12-21 16:41:58', '2012-12-21 16:55:39');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
